# -*- coding: utf-8 -*-
"""labwork1b.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uUPTiZooslBYHMta-PbqO3Qq7cDNro4q
"""

"""
Practical Work 1: Student Mark Management

"""

import random


# ---------------------- DATA HELPERS ----------------------

SURNAMES = ["Nguyen", "Tran", "Le", "Pham", "Hoang", "Huynh", "Phan",
            "Vu", "Vo", "Dang", "Bui", "Do", "Ho", "Ngo", "Duong", "Ly"]
MIDDLE_NAMES = ["Van", "Thi", "Khanh", "Minh", "Quoc", "Thanh", "Huu",
                "Ngoc", "Gia", "Kim", "Anh", "Duc"]
GIVEN_NAMES = ["Hung", "Anh", "Linh", "Nam", "Trang", "Huy", "Long",
               "Mai", "Yen", "Phuc", "Duc", "Trung", "Hoa", "Thu",
               "Tuan", "Hieu", "Quyen", "Chi", "Bao", "Khoa"]

MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
          "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]


def _ordinal(n):
    """Return day number with ordinal suffix, e.g. 8 -> '8th'."""
    if 10 <= n % 100 <= 20:
        suffix = "th"
    else:
        suffix = {1: "st", 2: "nd", 3: "rd"}.get(n % 10, "th")
    return f"{n}{suffix}"


def _random_name():
    return f"{random.choice(SURNAMES)} {random.choice(MIDDLE_NAMES)} {random.choice(GIVEN_NAMES)}"


def _random_dob(start_year=2005, end_year=2008):
    day = random.randint(1, 28)
    month = random.choice(MONTHS)
    year = random.randint(start_year, end_year)
    return f"{_ordinal(day)} {month} {year}"


def generate_demo_students(n=140):

    students = [{
        "id": "2510437",
        "name": "Nguyen Khanh Hung",
        "dob": "8th Sep 2007",
    }]

    start_id = 2510437
    for i in range(1, n):
        students.append({
            "id": str(start_id + i),
            "name": _random_name(),
            "dob": _random_dob(),
        })
    return students


def generate_random_marks(students, courses, marks, low=15.0, high=18.0):
    if not courses:
        print("No courses available. Please add courses first.")
        return marks
    if not students:
        print("No students available. Please add/generate students first.")
        return marks

    list_courses(courses)
    course_id = input("Enter course ID to auto-generate marks for: ").strip()
    course = find_course(courses, course_id)
    if course is None:
        print("Course not found.")
        return marks

    if course_id not in marks:
        marks[course_id] = {}

    for student in students:
        mark = round(random.uniform(low, high), 1)
        marks[course_id][student["id"]] = mark

    print(f"Generated random marks ({low}-{high}) for {len(students)} "
          f"students in {course['name']} ({course['id']}).")
    return marks


# ---------------------- INPUT FUNCTIONS ----------------------

def input_students(existing_students):

    n = int(input("Enter number of students to add: "))
    for i in range(n):
        print(f"\nStudent {len(existing_students) + 1}:")
        sid = input("  ID: ").strip()
        name = input("  Name: ").strip()
        dob = input("  Date of Birth (dd/mm/yyyy): ").strip()
        existing_students.append({"id": sid, "name": name, "dob": dob})
    return existing_students


def input_courses(existing_courses):

    n = int(input("Enter number of courses to add: "))
    for i in range(n):
        print(f"\nCourse {len(existing_courses) + 1}:")
        cid = input("  ID: ").strip()
        name = input("  Name: ").strip()
        existing_courses.append({"id": cid, "name": name})
    return existing_courses


def input_marks(students, courses, marks):
    if not courses:
        print("No courses available. Please add courses first.")
        return marks

    list_courses(courses)
    course_id = input("Enter course ID to enter marks for: ").strip()
    course = find_course(courses, course_id)
    if course is None:
        print("Course not found.")
        return marks

    if not students:
        print("No students available. Please add students first.")
        return marks

    if course_id not in marks:
        marks[course_id] = {}

    print(f"\nEntering marks for course: {course['name']} ({course['id']})")
    for student in students:
        while True:
            raw = input(f"  Mark for {student['name']} ({student['id']}): ").strip()
            try:
                mark = float(raw)
                break
            except ValueError:
                print("  Please enter a valid number.")
        marks[course_id][student["id"]] = mark

    return marks


# ---------------------- HELPER FUNCTIONS ----------------------

def find_course(courses, course_id):
    for course in courses:
        if course["id"] == course_id:
            return course
    return None


def find_student(students, student_id):
    for student in students:
        if student["id"] == student_id:
            return student
    return None


# ---------------------- LISTING FUNCTIONS ----------------------

def list_courses(courses):
    print("\n--- Course List ---")
    if not courses:
        print("No courses available.")
        return
    print(f"{'ID':<12}{'Name':<35}")
    print("-" * 47)
    for course in courses:
        print(f"{course['id']:<12}{course['name']:<35}")


def list_students(students):
    print("\n--- Student List ---")
    if not students:
        print("No students available.")
        return
    print(f"{'ID':<12}{'Name':<30}{'DoB':<15}")
    print("-" * 57)
    for student in students:
        print(f"{student['id']:<12}{student['name']:<30}{student['dob']:<15}")


def show_marks(students, courses, marks):
    list_courses(courses)
    course_id = input("Enter course ID to view marks: ").strip()
    course = find_course(courses, course_id)
    if course is None:
        print("Course not found.")
        return

    if course_id not in marks or not marks[course_id]:
        print(f"No marks recorded yet for course {course['name']} ({course['id']}).")
        return

    print(f"\n--- Marks for {course['name']} ({course['id']}) ---")
    print(f"{'ID':<12}{'Name':<30}{'Mark':<10}")
    print("-" * 52)
    for student_id, mark in marks[course_id].items():
        student = find_student(students, student_id)
        name = student["name"] if student else "Unknown"
        print(f"{student_id:<12}{name:<30}{mark:<10}")


# ---------------------- MENU / MAIN ----------------------

def show_menu():
    print("\n===== Student Mark Management =====")
    print("1. Input Students (manual)")
    print("2. Generate Demo Students (140, random names)")
    print("3. Input Courses")
    print("4. Input Marks (manual)")
    print("5. Auto-generate Random Marks for a Course (15-18)")
    print("6. List Courses")
    print("7. List Students")
    print("8. Show Marks for a Course")
    print("0. Exit")


def main():
    students = []   # list of dicts: {"id", "name", "dob"}
    courses = []    # list of dicts: {"id", "name"}
    marks = {}      # nested dict: marks[course_id][student_id] = mark

    while True:
        show_menu()
        choice = input("Enter your choice: ").strip()

        if choice == "1":
            students = input_students(students)
        elif choice == "2":
            students = generate_demo_students(140)
            print("Generated 140 demo students.")
        elif choice == "3":
            courses = input_courses(courses)
        elif choice == "4":
            marks = input_marks(students, courses, marks)
        elif choice == "5":
            marks = generate_random_marks(students, courses, marks)
        elif choice == "6":
            list_courses(courses)
        elif choice == "7":
            list_students(students)
        elif choice == "8":
            show_marks(students, courses, marks)
        elif choice == "0":
            print("Exiting program. Goodbye!")
            break
        else:
            print("Invalid choice. Please try again.")


if __name__ == "__main__":
    main()