# -*- coding: utf-8 -*-
"""labwork1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G_lNzwpFj_yTv-eEvHPfFYBIBWoOA2gY
"""

import math

radius = float(input("Enter circle radius? "))

area = math.pi * (radius**2)

print(f"Circle area = {area:.1f}")

celsius = float(input("Enter the temperature in Celsius? "))

fahrenheit = celsius * 9 / 5 + 32

print(f"{int(celsius) if celsius.is_integer() else celsius} (C) = {fahrenheit:.1f} (F)")

num = int(input("Enter a number? "))


if num > 1:
    is_prime = True
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            is_prime = False
            break
    if is_prime:
        print(f"{num} is a prime number")
    else:
        print(f"{num} is a NOT prime number")
else:
    print(f"{num} is a NOT prime number")

import math

def is_prime(k):
    if k <= 1:
        return False
    for i in range(2, int(math.isqrt(k)) + 1):
        if k % i == 0:
            return False
    return True

def is_perfect(num):
    if num <= 0 or num % 2 != 0:
        return False  # All known perfect numbers are even positive integers

    n = 1
    while True:
        mersenne_candidate = (1 << (n + 1)) - 1  # Equivalent to 2^(n+1) - 1
        formula_val = (1 << n) * mersenne_candidate  # Equivalent to 2^n * (2^(n+1) - 1)

        if formula_val == num:
            # Check Euclid-Euler condition: n+1 and (2^(n+1) - 1) must both be prime
            return is_prime(n + 1) and is_prime(mersenne_candidate)

        if formula_val > num:
            return False

        n += 1

num = int(input("Enter a number? "))

if is_perfect(num):
    print(f"{num} is a perfect number")
else:
    print(f"{num} is a NOT perfect number")

color_list = ["Black", "White", "Blue", "Red", "Green", "Yellow", "Orange", "Purple", "Pink", "Brown"]

user_color = input("What is your favorite color? ").strip()

if user_color in color_list:
    index = color_list.index(user_color)
    print(f"Your color is at index {index} in my list")
else:
    print("Sorry, I could not find your color")

for i in range (0,7,1):
    print (i, end= ", ")
print("\n")

for j in range (1,11,3):
    print (j, end= ", ")
print("\n")

for k in range (5,0,-1):
    print (k, end=", ")
print("\n")

for t in range (6,-3,-2):
    print (t, end=", ")
print("\n")

def remove_dollar_sign(s):
    return s.replace("$", "")

s = input("Enter a string: ")
print(remove_dollar_sign(s))

def extract_even(l):
    return [x for x in l if x % 2 == 0]

l = list(map(int, input().split()))
print(extract_even(l))

def factorial(n):
    if n < 0:      # only reject negative numbers
        return -1  # prevent the negative
    product = 1
    for i in range(1, n+1):
        product = product * i
    return product

u = int(input())
print(factorial(u))

def divisor(n):
    sum = []
    if n <= 1:
        sum.append(1)
        return sum
    else:
        for i in range(1, int(n**0.5) + 1):
            if n % i == 0:
                sum.append(i)
                if i != n // i:
                    sum.append(n // i)
        sum.sort()
        return sum

x = int(input())
print(divisor(x))

x1, y1 = map(float,input().split())
x2, y2 = map(float,input().split())
print(((x1-x2)**2 + (y1-y2)**2)**0.5)

m, n = map(int,input().split())
print("* " * m)
for i in range (1, n-1):
    print("* " + (m-2)*"  " + "* ")
print("* " * m)

x1, y1, x2, y2 = map(float, input("Input x1, y1, x2, y2: ").split())
print(((x1 - x2)**2 + (y1 - y2)**2)**0.5)

m, n = map(int, input().split()); print("\n".join("* " * n if i == 0 or i == m-1 else "* " + "  " * (n-2) + "*" for i in range(m)))